swagger: "2.0"

info:
  description: "旅先等での移動経路を保存するAPI"
  version: "1.0.0"
  title: "travel-route-api"
  contact:
    email: "chinoknct@gmail.com"
  license:
    name: "MIT License"
    url: "https://github.com/cotton-alta/travel-route-api/blob/main/LICENSE"

host: "www.example.com"
basePath: "/v1"

tags:
- name: "segment"
  description: "緯度経度の時系列データ"
- name: "point"
  description: "緯度経度データ"

schemes:
- "https"

paths:
  /segment:
    post:
      tags:
      - "segment"
      summary: "Add a new segment"
      description: ""
      operationId: "addSegment"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Segment object that needs to be added to database"
        required: true
        schema:
          $ref: "#/definitions/Segment"
      responses:
        "405":
          description: "Invalid input"
      security:
      - api_key: []

  /segment/{segmentId}:
    get:
      tags:
      - "segment"
      summary: "Find segment by ID"
      description: "Returns a single segment"
      operationId: "getSegmentById"
      produces:
      - "application/json"
      parameters:
      - name: "segmentId"
        in: "path"
        description: "ID of segment to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Segment"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Segment not found"
      security:
      - api_key: []

    put:
      tags:
      - "segment"
      summary: "Updates a segment"
      description: ""
      operationId: "updatePetWithForm"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "segmentId"
        in: "path"
        description: "ID of segment to return"
        required: true
        type: "integer"
        format: "int64"
      - name: "body"
        in: "body"
        description: "ID of pet that needs to be updated"
        required: true
        schema:
          $ref: "#/definitions/Segment"
      responses:
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Pet not found"
        "405":
          description: "Invalid input"
      security:
      - api_key: []

    delete:
      tags:
      - "segment"
      summary: "Deletes a segment"
      description: ""
      operationId: "deletePet"
      produces:
      - "application/json"
      parameters:
      - name: "api_key"
        in: "header"
        required: false
        type: "string"
      - name: "segmentId"
        in: "path"
        description: "Pet id to delete"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Pet not found"
      security:
        - api_key: []

securityDefinitions:
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"

definitions:
  Segment:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
        example: "segment title"
      points:
        type: "array"
        items:
          $ref: "#/definitions/Point"

  Point:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"